### ISSUE TITLE
Emails errados

### ISSUE THREAD

**Issue by lowerthansound** [araraonline/Mudda-Site#3]
Quando o email tá errado, o github não reconhece que é da pessoa em alguns lugares.

Malz zin. :(

@Hintaw Passa seu email do github aeh pra eu arrumar o que a gente já fez.

**Comment by MHAlmeida57** [comment]
que? hintaw@gmail.com

**Comment by lowerthansound** [comment]
eh hintaw memo? AUHU

**Comment by MHAlmeida57** [comment]
me explica direito carai vai wpp kkk

**Comment by MHAlmeida57** [comment]
hintaw57@gmail.com

**Comment by lowerthansound** [comment]
peraeh, to entrano
